/**
 * @file color.h
 * @author yeqiang_xu <yeqiang_xu@maxio-tech.com>
 * @brief 
 * @version 0.1
 * @date 2022-11-22
 * 
 * @copyright Copyright (c) 2022
 * 
 */

#ifndef _UAPI_LOG_COLOR_H_
#define _UAPI_LOG_COLOR_H_

/*
 * Format: \033[ + attr
 * Example: \033[1m\033[47;31m - flicker, white background, red font
 */
#define __COLOR_PREFIX			"\033["
#define __COLOR_SUFFIX			"m"
#define __COLOR_SEPARATOR		";"

#define __COLOR_ATTR_NONE		"0"
#define __COLOR_ATTR_BOLD		"1"
#define __COLOR_ATTR_UNDERLINE		"4"
#define __COLOR_ATTR_FLICKER		"5"
#define __COLOR_ATTR_REVERSE		"7"
#define __COLOR_ATTR_HIDE		"8"

#define __COLOR_FONT_BLACK		"30"
#define __COLOR_FONT_RED		"31"
#define __COLOR_FONT_GREEN		"32"
#define __COLOR_FONT_YELLOW		"33"
#define __COLOR_FONT_BLUE		"34"
#define __COLOR_FONT_PURPLE		"35"
#define __COLOR_FONT_CYAN		"36"
#define __COLOR_FONT_WHITE		"37"

#define __COLOR_BG_BLACK		"40"
#define __COLOR_BG_RED			"41"
#define __COLOR_BG_GREEN		"42"
#define __COLOR_BG_YELLOW		"43"
#define __COLOR_BG_BLUE			"44"
#define __COLOR_BG_PURPLE		"45"
#define __COLOR_BG_CYAN			"46"
#define __COLOR_BG_WHITE		"47"


/*
 * Format: LOG_[Attribute]_[Font color]_[Background color]
 */
#define LOG_N \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SUFFIX

/* Font color */
#define LOG_N_BLACK \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SEPARATOR __COLOR_FONT_BLACK __COLOR_SUFFIX
#define LOG_B_BLACK \
	__COLOR_PREFIX __COLOR_ATTR_BOLD __COLOR_SEPARATOR __COLOR_FONT_BLACK __COLOR_SUFFIX

#define LOG_N_RED \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SEPARATOR __COLOR_FONT_RED __COLOR_SUFFIX
#define LOG_B_RED \
	__COLOR_PREFIX __COLOR_ATTR_BOLD __COLOR_SEPARATOR __COLOR_FONT_RED __COLOR_SUFFIX
#define LOG_U_RED \
	__COLOR_PREFIX __COLOR_ATTR_UNDERLINE __COLOR_SEPARATOR __COLOR_FONT_RED __COLOR_SUFFIX
#define LOG_F_RED \
	__COLOR_PREFIX __COLOR_ATTR_FLICKER __COLOR_SEPARATOR __COLOR_FONT_RED __COLOR_SUFFIX
#define LOG_R_RED \
	__COLOR_PREFIX __COLOR_ATTR_REVERSE __COLOR_SEPARATOR __COLOR_FONT_RED __COLOR_SUFFIX
#define LOG_H_RED \
	__COLOR_PREFIX __COLOR_ATTR_HIDE __COLOR_SEPARATOR __COLOR_FONT_RED __COLOR_SUFFIX

#define LOG_N_GREEN \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SEPARATOR __COLOR_FONT_GREEN __COLOR_SUFFIX
#define LOG_B_GREEN \
	__COLOR_PREFIX __COLOR_ATTR_BOLD __COLOR_SEPARATOR __COLOR_FONT_GREEN __COLOR_SUFFIX
#define LOG_U_GREEN \
	__COLOR_PREFIX __COLOR_ATTR_UNDERLINE __COLOR_SEPARATOR __COLOR_FONT_GREEN __COLOR_SUFFIX
#define LOG_F_GREEN \
	__COLOR_PREFIX __COLOR_ATTR_FLICKER __COLOR_SEPARATOR __COLOR_FONT_GREEN __COLOR_SUFFIX

#define LOG_N_YELLOW \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SEPARATOR __COLOR_FONT_YELLOW __COLOR_SUFFIX
#define LOG_B_YELLOW \
	__COLOR_PREFIX __COLOR_ATTR_BOLD __COLOR_SEPARATOR __COLOR_FONT_YELLOW __COLOR_SUFFIX
#define LOG_U_YELLOW \
	__COLOR_PREFIX __COLOR_ATTR_UNDERLINE __COLOR_SEPARATOR __COLOR_FONT_YELLOW __COLOR_SUFFIX
#define LOG_F_YELLOW \
	__COLOR_PREFIX __COLOR_ATTR_FLICKER __COLOR_SEPARATOR __COLOR_FONT_YELLOW __COLOR_SUFFIX

#define LOG_N_BLUE \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SEPARATOR __COLOR_FONT_BLUE __COLOR_SUFFIX
#define LOG_B_BLUE \
	__COLOR_PREFIX __COLOR_ATTR_BOLD __COLOR_SEPARATOR __COLOR_FONT_BLUE __COLOR_SUFFIX

#define LOG_N_PURPLE \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SEPARATOR __COLOR_FONT_PURPLE __COLOR_SUFFIX
#define LOG_B_PURPLE \
	__COLOR_PREFIX __COLOR_ATTR_BOLD __COLOR_SEPARATOR __COLOR_FONT_PURPLE __COLOR_SUFFIX

#define LOG_N_CYAN \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SEPARATOR __COLOR_FONT_CYAN __COLOR_SUFFIX
#define LOG_B_CYAN \
	__COLOR_PREFIX __COLOR_ATTR_BOLD __COLOR_SEPARATOR __COLOR_FONT_CYAN __COLOR_SUFFIX

#define LOG_N_WHITE \
	__COLOR_PREFIX __COLOR_ATTR_NONE __COLOR_SEPARATOR __COLOR_FONT_WHITE __COLOR_SUFFIX
#define LOG_B_WHITE \
	__COLOR_PREFIX __COLOR_ATTR_BOLD __COLOR_SEPARATOR __COLOR_FONT_WHITE __COLOR_SUFFIX

/* Font and Background color */
#define LOG_N_CYAN_WHITE \
	__COLOR_PREFIX __COLOR_BG_WHITE __COLOR_SEPARATOR __COLOR_FONT_CYAN __COLOR_SUFFIX
#define LOG_F_CYAN_WHITE \
	__COLOR_PREFIX __COLOR_ATTR_FLICKER __COLOR_SUFFIX \
	__COLOR_PREFIX __COLOR_BG_WHITE __COLOR_SEPARATOR __COLOR_FONT_CYAN __COLOR_SUFFIX

#define LOG_N_WHITE_WHITE \
	__COLOR_PREFIX __COLOR_BG_WHITE __COLOR_SEPARATOR __COLOR_FONT_WHITE __COLOR_SUFFIX


#endif /* !_UAPI_LOG_COLOR_H_ */
