
__COLOR_PREFIX="\033["
__COLOR_SUFFIX="m"
__COLOR_SEPARATOR=";"

__COLOR_ATTR_NONE="0"
__COLOR_ATTR_BOLD="1"
__COLOR_ATTR_UNDERLINE="4"
__COLOR_ATTR_FLICKER="5"
__COLOR_ATTR_REVERSE="7"
__COLOR_ATTR_HIDE="8"

__COLOR_FONT_BLACK="30"
__COLOR_FONT_RED="31"
__COLOR_FONT_GREEN="32"
__COLOR_FONT_YELLOW="33"
__COLOR_FONT_BLUE="34"
__COLOR_FONT_PURPLE="35"
__COLOR_FONT_CYAN="36"
__COLOR_FONT_WHITE="37"

__COLOR_BG_BLACK="40"
__COLOR_BG_RED="41"
__COLOR_BG_GREEN="42"
__COLOR_BG_YELLOW="43"
__COLOR_BG_BLUE="44"
__COLOR_BG_PURPLE="45"
__COLOR_BG_CYAN="46"
__COLOR_BG_WHITE="47"

LOG_N=${__COLOR_PREFIX}${__COLOR_ATTR_NONE}${__COLOR_SUFFIX}

# --------------------------------------------------------------------------- #
# Font color
# --------------------------------------------------------------------------- #
LOG_N_BLACK=${__COLOR_PREFIX}${__COLOR_FONT_BLACK}${__COLOR_SUFFIX}
LOG_B_BLACK=${__COLOR_PREFIX}${__COLOR_ATTR_BOLD}${__COLOR_SEPARATOR}${__COLOR_FONT_BLACK}${__COLOR_SUFFIX}

LOG_N_RED=${__COLOR_PREFIX}${__COLOR_FONT_RED}${__COLOR_SUFFIX}
LOG_B_RED=${__COLOR_PREFIX}${__COLOR_ATTR_BOLD}${__COLOR_SEPARATOR}${__COLOR_FONT_RED}${__COLOR_SUFFIX}
LOG_U_RED=${__COLOR_PREFIX}${__COLOR_ATTR_UNDERLINE}${__COLOR_SEPARATOR}${__COLOR_FONT_RED}${__COLOR_SUFFIX}
LOG_F_RED=${__COLOR_PREFIX}${__COLOR_ATTR_FLICKER}${__COLOR_SEPARATOR}${__COLOR_FONT_RED}${__COLOR_SUFFIX}
LOG_R_RED=${__COLOR_PREFIX}${__COLOR_ATTR_REVERSE}${__COLOR_SEPARATOR}${__COLOR_FONT_RED}${__COLOR_SUFFIX}
LOG_H_RED=${__COLOR_PREFIX}${__COLOR_ATTR_HIDE}${__COLOR_SEPARATOR}${__COLOR_FONT_RED}${__COLOR_SUFFIX}

LOG_N_GREEN=${__COLOR_PREFIX}${__COLOR_FONT_GREEN}${__COLOR_SUFFIX}
LOG_B_GREEN=${__COLOR_PREFIX}${__COLOR_ATTR_BOLD}${__COLOR_SEPARATOR}${__COLOR_FONT_GREEN}${__COLOR_SUFFIX}
LOG_U_GREEN=${__COLOR_PREFIX}${__COLOR_ATTR_UNDERLINE}${__COLOR_SEPARATOR}${__COLOR_FONT_GREEN}${__COLOR_SUFFIX}
LOG_F_GREEN=${__COLOR_PREFIX}${__COLOR_ATTR_FLICKER}${__COLOR_SEPARATOR}${__COLOR_FONT_GREEN}${__COLOR_SUFFIX}

LOG_N_YELLOW=${__COLOR_PREFIX}${__COLOR_FONT_YELLOW}${__COLOR_SUFFIX}
LOG_B_YELLOW=${__COLOR_PREFIX}${__COLOR_ATTR_BOLD}${__COLOR_SEPARATOR}${__COLOR_FONT_YELLOW}${__COLOR_SUFFIX}
LOG_U_YELLOW=${__COLOR_PREFIX}${__COLOR_ATTR_UNDERLINE}${__COLOR_SEPARATOR}${__COLOR_FONT_YELLOW}${__COLOR_SUFFIX}
LOG_F_YELLOW=${__COLOR_PREFIX}${__COLOR_ATTR_FLICKER}${__COLOR_SEPARATOR}${__COLOR_FONT_YELLOW}${__COLOR_SUFFIX}

LOG_N_BLUE=${__COLOR_PREFIX}${__COLOR_FONT_BLUE}${__COLOR_SUFFIX}
LOG_B_BLUE=${__COLOR_PREFIX}${__COLOR_ATTR_BOLD}${__COLOR_SEPARATOR}${__COLOR_FONT_BLUE}${__COLOR_SUFFIX}

LOG_N_PURPLE=${__COLOR_PREFIX}${__COLOR_FONT_PURPLE}${__COLOR_SUFFIX}
LOG_B_PURPLE=${__COLOR_PREFIX}${__COLOR_ATTR_BOLD}${__COLOR_SEPARATOR}${__COLOR_FONT_PURPLE}${__COLOR_SUFFIX}

LOG_N_CYAN=${__COLOR_PREFIX}${__COLOR_FONT_CYAN}${__COLOR_SUFFIX}
LOG_B_CYAN=${__COLOR_PREFIX}${__COLOR_ATTR_BOLD}${__COLOR_SEPARATOR}${__COLOR_FONT_CYAN}${__COLOR_SUFFIX}

LOG_N_WHITE=${__COLOR_PREFIX}${__COLOR_FONT_WHITE}${__COLOR_SUFFIX}
LOG_B_WHITE=${__COLOR_PREFIX}${__COLOR_ATTR_BOLD}${__COLOR_SEPARATOR}${__COLOR_FONT_WHITE}${__COLOR_SUFFIX}
